# Generated by Django 4.1.3 on 2022-11-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='members',
            field=models.IntegerField(default=1),
        ),
    ]
