# Generated by Django 4.1.3 on 2022-12-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_unit_building_alter_unit_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('built_up_area', models.FloatField()),
                ('bedroom', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('year_of_construction', models.IntegerField()),
                ('features', models.TextField(help_text='in a comma-seperated format')),
                ('description', models.TextField(null=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit')),
            ],
        ),
    ]
