# Generated by Django 4.1.3 on 2022-11-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('MANAGER', 'manager'), ('RESIDENT', 'resident')], max_length=8, null=True),
        ),
    ]
