# Generated by Django 4.1.3 on 2022-11-28 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_email_activated_user_is_phone_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(regex='^09(1[0-9]|3[1-9]|2[1-9])-?[0-9]{3}-?[0-9]{4}$')]),
        ),
    ]
