# Generated by Django 4.1.3 on 2022-11-29 11:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_unit_building_alter_unit_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_inbox_message_type_alter_inbox_seen_delete_outbox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InBox',
            new_name='Ticket',
        ),
    ]
