# Generated by Django 4.1.3 on 2022-11-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_inbox_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='message_type',
        ),
    ]
