# Generated by Django 4.1.3 on 2022-11-28 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=utils.helper.generate_otp)),
                ('expire_date', models.DateTimeField(default=utils.helper.generate_otp_expire_date)),
                ('otp_for', models.CharField(choices=[('EMAIL', 'email'), ('SMS', 'sms')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
