# Generated by Django 4.1.3 on 2022-11-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_otp_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_for',
            field=models.CharField(choices=[('EMAIL', 'email'), ('PHONE', 'sms')], max_length=5),
        ),
    ]
