# Generated by Django 4.1.3 on 2022-12-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_alter_unitspecification_features'),
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='unit',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='unit_specification',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buildings.unitspecification'),
            preserve_default=False,
        ),
    ]
