# Generated by Django 4.1.3 on 2022-12-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_remove_advertisement_owner_remove_advertisement_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='exchangeable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='mortgage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='rent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='what_for',
            field=models.CharField(choices=[('RENT', 'rent'), ('SALE', 'sale')], default="RENT", max_length=4),
            preserve_default=False,
        ),
    ]
