# Generated by Django 4.1.3 on 2022-11-28 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
