# Generated by Django 4.1.3 on 2022-12-11 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=225)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^09(1[0-9]|3[1-9]|2[1-9])-?[0-9]{3}-?[0-9]{4}$')])),
                ('message', models.TextField()),
            ],
        ),
    ]
